erDiagram
    %% Relaciones Conceptuales entre Bounded Contexts
    "AuthIdentity"      }o--o{ "SocialConnect"    : "Provee Identidad a"
    "AuthIdentity"      }o--o{ "MessagingService" : "Provee Identidad a"
    "AuthIdentity"      }o--o{ "RiskMitigation"   : "Provee Identidad a"
    "AuthIdentity"      }o--o{ "PasswordGuardian" : "Usa para Validar"
    "SocialConnect"     }o--o{ "RiskMitigation"   : "Es Analizado por"
    "RiskMitigation"    }o--o{ "ResourcesDocs"    : "Sugiere"

    %% Atributos de cada Bounded Context
    "AuthIdentity": "Subdominio: Soporte"
    "AuthIdentity": "Aggregate Root: User"
    "AuthIdentity": "Agregado: User-UserProfile"
    "AuthIdentity": "Value Objects: Email, HashedPassword"

    "SocialConnect": "Subdominio: Core (Principal)"
    "SocialConnect": "Aggregate Roots: Publication, UserNode"
    "SocialConnect": "Agregado: Publication-Media-Comments"
    "SocialConnect": "Value Objects: Location, MediaType"

    "MessagingService": "Subdominio: Soporte"
    "MessagingService": "Aggregate Root: Conversation"
    "MessagingService": "Agregado: Conversation-Participants-Messages"
    "MessagingService": "Value Objects: MessageStatus, Role"

    "RiskMitigation": "Subdominio: Core (Soporte al Principal)"
    "RiskMitigation": "Aggregate Root: RiskProfile"
    "RiskMitigation": "Agregado: RiskProfile"
    "RiskMitigation": "Value Objects: RiskScore, AnalysisResult"

    "ResourcesDocs": "Subdominio: Soporte"
    "ResourcesDocs": "Aggregate Root: Resource"
    "ResourcesDocs": "Agregado: Resource"
    "ResourcesDocs": "Value Objects: Category, ContentBlock"

    "PasswordGuardian": "Subdominio: Genérico"
    "PasswordGuardian": "Value Objects: PasswordToCheck"
