sequenceDiagram
    participant C as Cliente
    participant GW as API Gateway
    participant Auth as AuthIdentity
    participant Guard as PasswordGuardian
    participant Broker as RabbitMQ

    C->>+GW: POST /api/auth/register (user, email, pass)
    GW->>+Auth: POST /register (user, email, pass)
    Auth->>+Guard: POST /passwords/is-secure (pass)
    Guard-->>-Auth: 200 OK
    Note right of Auth: Valida email, username, etc.
    Auth->>Auth: Hashea la contraseña
    Auth->>Auth: Guarda usuario en BBDD
    Auth->>Broker: Publica evento 'UserRegistered'
    Auth-->>-GW: 201 Created
    GW-->>-C: 201 Created
